### ISSUE TITLE
Design document a "Rule Engine"

### ISSUE THREAD

**Issue by samvaity** [Njeriiii/CodeQualityAnalyzer#4]
Includes,
- data structure to define the rules
- the evaluation engine defining bad practices and suggestions
- documents integration workflow with the plugin

**Comment by Njeriiii** [comment]
Completed Doc: [Design Doc](https://microsoft-my.sharepoint.com/:w:/p/t-njmwenjwa/EaXA-JUbxNZBqhorUhJhMrcBIw87SSZs7n2cxN2s14bqiA?e=y0t7tA)
- This document describes the rule engine.

Iterations needed:
- Making 1 major rule engine that determines which rule to apply depending on the components of the file being analyzed, instead of analyzing the entire file once for each rule set (will come around week 7-8)
